# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:


- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: 'testtheory'
    configuration: |
      apiKey=521be16bdf6a4a999fd5553aa4973cfd50916946b1734b798c133d18aafeb71d
      gradle.resolveDependencies=true
      gradle.runAssembleCommand=true
      gradle.aggregateModules=true
      gradle.preferredEnvironment=gradle
      gradle.downloadMissingDependencies=true
      gradle.runPreStep=true
      gradle.ignoreSourceFiles=false
      gradle.preferredEnvironment=gradle
      gradle.innerModulesAsDependencies=true
      archiveExtractionDepth=10
      archiveIncludes=**/*.war **/*.ear **/*.zip **/*.gzip **/*.tar.bz2 **/*.tar.gz **/*.tgz **/*.tar
      #archiveExcludes=**/*sources.jar